import { Button, VerticalBox, ScrollView } from "std-widgets.slint";

struct WifiDevice {
    name: string,
    ip: string,
}

struct BlueDevice {
    identifier: string,
}

export component AppWindow inherits Window {
    width: 600px;
    height: 600px;
    in-out property <[WifiDevice]> wifi_devices: [];
    in-out property <[BlueDevice]> blue_devices: [];
    in-out property <bool> sending_file;
    in-out property <bool> blue_connected_menu;
    in-out property <bool> receiving_file: false;
    in-out property <string> transfer_status: "";

    callback send_select_device_wifi(string);
    callback send_select_device_blue(string);
    callback disconnect();
    callback file_accept();
    callback file_reject();
    
    if (!blue_connected_menu && !receiving_file): ScrollView {
        VerticalLayout {
            alignment: start;
            spacing: 10px;
            padding: 10px;

            Text {
                text: "Wi-Fi Devices";
                font-size: 16px;
                font-weight: 700;
            }

            VerticalLayout {
                spacing: 5px;
                for device[i] in wifi_devices: Button {
                    height: 40px;
                    text: device.name + " (" + device.ip + ") ";
                    clicked => {
                        self.text = "File Sent Successfully";
                        send_select_device_wifi(device.ip);
                    }
                }
            }

            Text {
                text: "Bluetooth Devices";
                font-size: 16px;
                font-weight: 700;
            }

            VerticalLayout {
                spacing: 5px;
                for device[i] in blue_devices: Button {
                    height: 40px;
                    text: device.identifier;
                    clicked => {
                        self.text = "Pairing";
                        send_select_device_blue(device.identifier);
                        blue_connected_menu = true;
                    }
                }
            }
        }
    }
    if (blue_connected_menu): Button {
        text: "Disconnect";
        clicked => {
            blue_connected_menu = false;
            disconnect();
        }
    }
    if (receiving_file): VerticalLayout {
        alignment: center;
        spacing: 10px;
        Button {
            primary: true;
            height: 50px;
            text: "Accept";
            clicked => {
                file_accept();
            }
        }
        Button {
            height: 50px;
            text: "Reject";
            clicked => {
                file_reject();
            }
        }
    }
}