[package]
name = "rustdrop"
version = "0.1.0"
edition = "2024"

[dependencies]
async-std = "1.13.2"
ble-peripheral-rust = "0.2.0"
bluest = "0.6.9"
chunked_transfer = "1.5.0"
futures-util = "0.3.32"
io = "0.0.2"
local-ip-address = "0.6.12"
mdns = "3.0.0"
mdns-sd = "0.19.1"
rfd = "0.17.2"
slint = "1.16.1"
tokio = { version = "1.52.3", features = ["rt-multi-thread", "time"] }

[build-dependencies]
slint-build = "1.16.1"

[lib]
crate-type = ["cdylib"]