[package]
name = "rustdrop"
version = "0.1.0"
edition = "2024"

[dependencies]
async-std = "1.13.2"
bluest = { version = "0.6.9", features = ["unstable"] }
chunked_transfer = "1.5.0"
futures-util = "0.3.32"
local-ip-address = "0.6.12"
mdns = "3.0.0"
mdns-sd = "0.19.1"
mimalloc = "0.1.50"
jni = "0.19.0"
slint = { version = "1.16.1", features = ["backend-android-activity-06"] }
tokio = { version = "1.52.3", features = ["rt-multi-thread", "time"] }

[target.'cfg(not(target_os = "android"))'.dependencies]
rfd = "0.17.2"
ble-peripheral-rust = "0.2.0"

[build-dependencies]
slint-build = "1.16.1"

[lib]
name = "rustdrop"
crate-type = ["cdylib", "lib"]

[package.metadata.android]
target_sdk_version = 36